/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BIT3_aliases.h"
#include "BIT3.h"
#include "DMA_In_dma.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "isr_dma_done.h"
#include "BIT2_aliases.h"
#include "BIT2.h"
#include "BIT1_aliases.h"
#include "BIT1.h"
#include "Filter_1.h"
#include "Filter_1_PVT.h"
#include "DMA_Out_dma.h"
#include "BUS_CLK_Ref.h"
#include "DMA_a_Comp_dma.h"
#include "Status_Reg_1.h"
#include "CtrlReg_Filtro_Out.h"
#include "OpAmp_Filtro1.h"
#include "Pin_Salida_F1_aliases.h"
#include "Pin_Salida_F1.h"
#include "OpAmp_Filtro2.h"
#include "Pin_Salida_F2_aliases.h"
#include "Pin_Salida_F2.h"
#include "OpAmp_Vref.h"
#include "Pin_TierraVirtual_aliases.h"
#include "Pin_TierraVirtual.h"
#include "Pin_Entrada_F1_aliases.h"
#include "Pin_Entrada_F1.h"
#include "Pin_Entrada_F2_aliases.h"
#include "Pin_Entrada_F2.h"
#include "PGA_1.h"
#include "ADC_DelSig_1.h"
#include "Pin_Salida_PGA_aliases.h"
#include "Pin_Salida_PGA.h"
#include "OpAmp_Acoplador.h"
#include "Vout_1_aliases.h"
#include "Vout_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

