# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\tobia\Downloads\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab\lab5-fiuna-filtros_sencillos\Design01.cydsn\Design01.cyprj
# Date: Wed, 05 Nov 2025 19:18:05 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 14.285714285714285 -waveform {0 7.14285714285714} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 14.285714285714285 -waveform {0 7.14285714285714} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {UART_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 77 153} -nominal_period 1085.7142857142856 [list [get_pins {ClockBlock/dclk_glb_0}]]


# Component constraints for C:\Users\tobia\Downloads\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab\lab5-fiuna-filtros_sencillos\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\tobia\Downloads\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab-20251102T203416Z-1-001\ProyectoPDS solo matlab\lab5-fiuna-filtros_sencillos\Design01.cydsn\Design01.cyprj
# Date: Wed, 05 Nov 2025 19:18:02 GMT
